name: Build
on: workflow_dispatch
defaults:
  run:
    shell: bash
jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      
      - uses: actions/setup-go@v7
        with:
          go-version: '1.26'  
      
      - run: go build -o helou -v .

      - name: Create deb package
        id: nfpm-deb
        uses: burningalchemist/action-gh-nfpm@v1
        with:
          packager: deb
          config: nfpm.yaml
          nfpm_version: 2.47.0
      
      - name: Create rpm package
        id: nfpm-rpm
        uses: burningalchemist/action-gh-nfpm@v1
        with:
          packager: rpm
          config: nfpm.yaml
          nfpm_version: 2.47.0
      
      - name: Upload deb
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.nfpm-deb.outputs.package }}
          archive: false

      - name: Upload rpm
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.nfpm-rpm.outputs.package }}
          archive: false
          
      - uses: actions/upload-artifact@v7
        with:
          path: helou
          archive: false
